[deployment]
deploymentTarget = "autoscale"
build = ["npm", "run", "build"]
run = ["npm", "run", "start"]
publicDir = "."
ignorePorts = false

[[ports]]
localPort = 5000
externalPort = 80

[deployment.env]
PORT = "5000"