// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxqpavxgunkllefkiwjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cXBhdnhndW5rbGxlZmtpd2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDQxNzMsImV4cCI6MjA3MDA4MDE3M30.8xeWOjMGCRggeufhkNyKcPjeo1Rz3l7n84fzYHQHQuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});